apiVersion: apps/v1

kind: Deployment

metadata:

  name: php

  labels:

    app: php

spec:

  replicas: 1

  selector:

    matchLabels:

      app: php

  template:

    metadata:

      labels:

        app: php

    spec:

      containers:

      - name: php

        image: 130329173591.dkr.ecr.us-east-1.amazonaws.com/my-docker-repo:latest

        ports:

        - containerPort: 80

       

       

---



apiVersion: v1

kind: Service

metadata:

  name: php

spec:

  selector:

    app: php

  type: LoadBalancer

  ports:

  - protocol: TCP

    port: 80

    targetPort: 80

    nodePort: 31115
