apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: phpapp
  name: php-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: phpapp
    spec:
      containers:
      - image: http://3.96.203.160:8082/myphpapp:1.13
        name: phpapp
        ports: 
        - name: phpapp
          containerPort: 8085
---
# Node Port Service
apiVersion: v1
kind: Service
metadata:
  labels:
    name: phpapp
  name: phpapp
spec:
  type: NodePort
  ports:
    - port: 8086
      targetPort: 8086
  selector:
    name: phpapp
---
